import { appendFile } from "node:fs/promises";
import { SignJWT } from "jose";
import superjson from "superjson";

const LIVE_ENDPOINT = "https://billionairecollection.com/api/trpc/news.upsertMany";
const publishedAt = new Date("2026-09-02T00:00:00.000Z");
const allowedCategories = new Set(["Wealth", "Real Estate", "Superyachts", "Aviation", "Automotive", "Art", "Philanthropy", "Luxury", "Technology", "Markets", "Family Offices"]);

export const articles = [
  { slug: "club-med-hong-kong-ipo-500-million-fosun-2026", title: "Fosun’s Club Med Files for a $500 Million Hong Kong IPO", summary: "Caproasia reports that Club Med, the premium resort business owned by billionaire Guo Guangchang’s Fosun Tourism, has filed for a Hong Kong IPO. The proposed listing is targeted for the second half of 2026 or 2027 and is expected to raise about $500 million.", category: "Markets", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/01/china-billionaire-guo-guangchang-fosun-tourism-group-subsidiary-premium-all-inclusive-resorts-club-med-files-hong-kong-ipo-plans-ipo-2026-2h-or-2027-to-raise-500-million-fosun-led-investor-group-ac/", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "ikonic-yachts-family-office-model-superyacht-ownership-2026", title: "Ikonic Yachts Brings a Family-Office Model to Superyacht Ownership", summary: "Forbes reports that Ikonic Yachts is positioning itself as an integrated adviser on acquisition, sale, charter and management for UHNW yacht owners. Its proprietary Sovereign platform draws on operational budgets and deal data to improve valuation and ownership-cost modelling.", category: "Family Offices", source: "Forbes", articleUrl: "https://www.forbes.com/sites/jefffromm/2026/09/01/ultra-high-net-worth-users-get-a-family-office-view-to-super-yachts/", imageUrl: "https://images.unsplash.com/photo-1544550285-f813152fb2fd?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "gabe-newell-leviathan-draak-monaco-yacht-show-2026", title: "Gabe Newell’s Leviathan Heads to Monaco With Support Yacht Draak", summary: "BOAT International reports that Gabe Newell’s 111-metre Oceanco Leviathan and 92.8-metre companion Draak departed Poole for the Mediterranean. The yachts are expected to attend the 2026 Monaco Yacht Show, where Leviathan will be the largest yacht displayed.", category: "Superyachts", source: "BOAT International", articleUrl: "https://www.boatinternational.com/yachts/news/superyachts-spotted-around-the-world", imageUrl: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "billionaire-philanthropy-donor-advised-funds-callahan-2026", title: "The New Philanthropy Is Being Shaped by Concentrated Private Wealth", summary: "Sarasota Magazine’s interview with Inside Philanthropy founder David Callahan examines the expanding influence of billionaire and UHNW giving. Callahan points to the growth of donor-advised funds and private foundations, as well as a generation of donors seeking measurable impact.", category: "Philanthropy", source: "Sarasota Magazine", articleUrl: "https://www.sarasotamagazine.com/news-and-profiles/2026/09/the-new-philanthropy", imageUrl: "https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "trophy-art-market-billionaire-collector-concentration-2026", title: "Trophy-Art Sales Become More Dependent on Billionaire Collectors", summary: "The Art Newspaper reports that wealth inequality is increasingly linked to concentration at the top of the art market. Research cited in the article found that fewer than 0.3% of auction lots sold in 2025 accounted for almost 45% of global auction sales by value.", category: "Art", source: "The Art Newspaper", articleUrl: "https://www.theartnewspaper.com/2026/09/01/the-art-worlds-billionaire-problem-is-getting-worse", imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "herbert-wertheim-ferrari-luce-40-million-charity-auction-2026", title: "Billionaire Herbert Wertheim’s $40 Million Ferrari Luce Bid Supports Education", summary: "Fortune reports that billionaire philanthropist Herbert A. Wertheim paid $40 million for Ferrari’s first Luce at a Sotheby’s charity auction. The proceeds benefit the Ferrari Foundation’s education initiatives, while the sale brought attention to the tax treatment of major charitable purchases.", category: "Automotive", source: "Fortune", articleUrl: "https://fortune.com/2026/08/28/american-billionaire-ferrari-luce-tax-break-40-million-philanthropy/", imageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "shahid-khan-whisper-149-million-superyacht-sale-2026", title: "Shahid Khan’s Whisper Offers a €149 Million Ready-to-Cruise Alternative", summary: "Forbes reports that the 95.2-metre Lürssen Whisper, commissioned by billionaire Shahid Khan, is listed at €149 million. The broker estimates that a comparable new build could cost close to €400 million and take four to five years to deliver.", category: "Superyachts", source: "Forbes", articleUrl: "https://www.forbes.com/sites/deajusufi/2026/08/29/this-superyacht-could-save-its-next-owner-250-million-and-five-years/", imageUrl: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "french-riviera-monaco-billionaire-travel-ranking-2026", title: "French Riviera and Monaco Lead the Billionaire Travel Map", summary: "Yahoo Creators reports that the French Riviera and Monaco lead a ranking of ultra-luxury destinations based on private-aviation access, five-star hotel and villa density, elite leisure and luxury pricing. The report frames privacy, logistics and yacht access as core elements of UHNW travel demand.", category: "Luxury", source: "Yahoo Creators", articleUrl: "https://creators.yahoo.com/lifestyle/story/10-ultra-luxury-billionaire-vacation-spots--where-the-worlds-richest-people-go-to-disappear-220115415.html", imageUrl: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "altea-hills-7-million-mediterranean-villa-2026", title: "A $7 Million Altea Hills Villa Brings Mediterranean Luxury to Market", summary: "Robb Report reports that a 9,600-square-foot villa in the Altea Hills enclave near Alicante is available for just under $7 million. The three-level property combines 180-degree sea views with an infinity pool, cinema, gym, sauna and terraced gardens.", category: "Real Estate", source: "Robb Report", articleUrl: "https://robbreport.com/shelter/homes-for-sale/spain-altea-hills-villa-1238609439/", imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "electric-air-taxis-limited-commercial-service-2026", title: "Electric Air Taxis Move Toward First Limited Passenger Services", summary: "Robb Report reports that the first limited eVTOL passenger services may begin in 2026, with Joby Aviation among the leading contenders. Early deployment is expected to focus on short, premium city connections between airports, heliports and dedicated vertiports.", category: "Aviation", source: "Robb Report", articleUrl: "https://robbreport.com/motors/aviation/electric-air-taxis-take-flight-what-to-expect-1238574064/", imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "chanel-imprime-lion-20-carat-sapphire-necklace-2026", title: "Chanel’s Imprimé Lion Necklace Centres on a 20-Carat Sapphire", summary: "Robb Report reports that Chanel’s Signes & Symboles high-jewellery collection is led by the Imprimé Lion necklace with a 20.66-carat Sri Lankan sapphire. The piece blends diamonds, white and rose gold, and is said to require 1,800 hours of craftsmanship.", category: "Luxury", source: "Robb Report", articleUrl: "https://robbreport.com/style/jewelry/chanel-imprime-lion-necklace-1238574074/", imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "porsche-911-challenge-customer-race-car-2026", title: "Porsche Unveils the $275,000 911 Challenge Customer Racer", summary: "Robb Report reports that Porsche’s 911 Challenge will replace the 718 Cayman GT4 RS Clubsport at the entry point of its customer-racing range. The track-only 508-horsepower model is expected to join one-make competition from the 2027 season.", category: "Automotive", source: "Robb Report", articleUrl: "https://robbreport.com/motors/cars/porsche-911-challenge-entry-level-race-car-1238607226/", imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80", isFeatured: false, publishedAt },
];

function requireEnv(name) { const value = process.env[name]; if (!value) throw new Error(`${name} is not set`); return value; }
function validateBatch() {
  if (articles.length !== 12) throw new Error("Expected exactly 12 articles");
  if (articles.filter(article => article.isFeatured).length !== 2) throw new Error("Expected exactly 2 featured articles");
  const slugs = new Set();
  for (const article of articles) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(article.slug)) throw new Error(`Invalid slug: ${article.slug}`);
    if (slugs.has(article.slug)) throw new Error(`Duplicate slug: ${article.slug}`);
    if (!allowedCategories.has(article.category)) throw new Error(`Invalid category: ${article.category}`);
    if (!/^https:\/\/images\.unsplash\.com\/photo-[A-Za-z0-9-]+\?w=800&q=80$/.test(article.imageUrl)) throw new Error(`Invalid Unsplash URL: ${article.slug}`);
    if (article.publishedAt.toISOString() !== "2026-09-02T00:00:00.000Z") throw new Error(`Invalid publication date: ${article.slug}`);
    if (!article.title || !article.summary || !article.source || !article.articleUrl) throw new Error(`Missing required field: ${article.slug}`);
    slugs.add(article.slug);
  }
}

try {
  validateBatch();
  const secret = new TextEncoder().encode(requireEnv("JWT_SECRET"));
  const now = Math.floor(Date.now() / 1000);
  const token = await new SignJWT({ openId: requireEnv("OWNER_OPEN_ID"), appId: requireEnv("VITE_APP_ID"), name: process.env.OWNER_NAME || "Billionaire Collection Owner" }).setProtectedHeader({ alg: "HS256", typ: "JWT" }).setIssuedAt(now).setExpirationTime(now + 300).sign(secret);
  const response = await fetch(LIVE_ENDPOINT, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify(superjson.serialize(articles)) });
  const responseText = await response.text();
  if (!response.ok) throw new Error(`Live tRPC request failed with HTTP ${response.status}: ${responseText}`);
  console.log(JSON.stringify({ success: true, count: articles.length, response: responseText }));
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  await appendFile("/tmp/billionaire-collection-news-upsert-2026-09-02.error.log", `${new Date().toISOString()} ${message}\n`);
  console.error(message);
  process.exitCode = 1;
}
