import { appendFile } from "node:fs/promises";
import { SignJWT } from "jose";
import superjson from "superjson";

const LIVE_ENDPOINT = "https://billionairecollection.com/api/trpc/news.upsertMany";
const publishedAt = new Date("2026-09-03T00:00:00.000Z");
const allowedCategories = new Set(["Wealth", "Real Estate", "Superyachts", "Aviation", "Automotive", "Art", "Philanthropy", "Luxury", "Technology", "Markets", "Family Offices"]);

export const articles = [
  { slug: "1789-capital-polymarket-300-million-investment-2026", title: "1789 Capital Targets $300 Million Polymarket Investment at a $21 Billion Valuation", summary: "Caproasia reports that 1789 Capital, the venture-capital firm associated with Donald Trump Jr., is to invest $300 million in Polymarket. The investment values the prediction-market company at $21 billion, placing it firmly in the current conversation around alternative market infrastructure.", category: "Markets", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/02/united-states-president-billionaire-donald-trump-age-80-eldest-son-donald-trump-jr-venture-capital-firm-1789-capital-to-invest-300-million-in-united-states-prediction-market-company-polymarket-at/", imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "softbank-sb-energy-7-billion-nasdaq-ipo-2026", title: "Masayoshi Son’s SB Energy Files for a $7 Billion Nasdaq IPO", summary: "Caproasia reports that SoftBank Group subsidiary SB Energy has filed for a Nasdaq IPO seeking to raise $7 billion at a $50 billion valuation. The 2019-founded power and data-centre infrastructure company is positioned around capacity for the AI economy.", category: "Technology", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/02/japan-billionaire-masayoshi-son-softbank-group-subsidiary-sb-energy-files-for-nasdaq-ipo-to-raise-7-billion-at-50-billion-valuation-founded-in-2019-by-softbank-group/", imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "lurssen-six-custom-superyacht-deliveries-2026", title: "Lürssen Delivers Six Full-Custom Superyachts in a Single Year", summary: "Forbes reports that German shipyard Lürssen has delivered six full-custom yachts in 2026, ranging from 75 to 140 metres. The lineup includes ODISEA, DEEP BLUE, BOARDWALK, O3, NAUSICAÄ and NIXIE, the latter incorporating hybrid diesel-electric propulsion and energy storage.", category: "Superyachts", source: "Forbes", articleUrl: "https://www.forbes.com/sites/billspringer/2026/09/02/lrssen-launch-unprecedented-6-new-superyachts-in-2026/", imageUrl: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "monterey-car-week-762-million-next-generation-collectors-2026", title: "Next-Generation Collectors Drive Monterey Car Week to $762 Million", summary: "Art & Object reports that the five leading auction houses at Monterey Car Week achieved a record $762 million in sales, up 76% year on year. Demand was particularly strong for modern supercars, with the article identifying a rising influence from younger collectors and technology wealth.", category: "Automotive", source: "Art & Object", articleUrl: "https://www.artandobject.com/news/what-montereys-762-million-car-week-says-about-whos-buying", imageUrl: "https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "club-med-hong-kong-ipo-fosun-500-million-2026", title: "Fosun’s Club Med Files for a $500 Million Hong Kong IPO", summary: "Caproasia reports that Club Med, the premium resort business owned by billionaire Guo Guangchang’s Fosun Tourism, has filed for a Hong Kong IPO. The proposed listing is expected to raise approximately $500 million in late 2026 or 2027.", category: "Luxury", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/01/china-billionaire-guo-guangchang-fosun-tourism-group-subsidiary-premium-all-inclusive-resorts-club-med-files-hong-kong-ipo-plans-ipo-2026-2h-or-2027-to-raise-500-million-fosun-led-investor-group-ac/", imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "ikonic-yachts-family-office-advisory-model-2026", title: "Ikonic Yachts Introduces a Family-Office Advisory Model for Owners", summary: "Forbes reports that Ikonic Yachts integrates acquisition, sale, charter and management in a service model designed for UHNW owners and their offices. Its Sovereign platform uses operating budgets and deal data to inform valuation, ownership costs, timing, compliance and risk discussions.", category: "Family Offices", source: "Forbes", articleUrl: "https://www.forbes.com/sites/jefffromm/2026/09/01/ultra-high-net-worth-users-get-a-family-office-view-to-super-yachts/", imageUrl: "https://images.unsplash.com/photo-1544550285-f813152fb2fd?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "trophy-art-market-ultra-wealthy-collectors-2026", title: "Trophy-Art Market Grows More Dependent on Ultra-Wealthy Collectors", summary: "The Art Newspaper reports that a small number of museum-quality works and ultra-wealthy buyers account for an increasing portion of auction activity. Research cited by the publication found that fewer than 0.3% of works sold at auction in 2025 generated almost 45% of global auction sales by value.", category: "Art", source: "The Art Newspaper", articleUrl: "https://www.theartnewspaper.com/2026/09/01/the-art-worlds-billionaire-problem-is-getting-worse", imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "herbert-wertheim-ferrari-luce-40-million-charity-auction-2026", title: "Herbert Wertheim’s $40 Million Ferrari Luce Bid Puts Philanthropy in the Spotlight", summary: "Fortune reports that billionaire philanthropist Herbert A. Wertheim paid $40 million for Ferrari’s first Luce in a Sotheby’s charity auction. The proceeds benefit the Ferrari Foundation’s education work, while the transaction highlights the tax treatment of exceptional charitable purchases.", category: "Philanthropy", source: "Fortune", articleUrl: "https://fortune.com/2026/08/28/american-billionaire-ferrari-luce-tax-break-40-million-philanthropy/", imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "shahid-khan-whisper-149-million-ready-superyacht-2026", title: "Shahid Khan’s Whisper Offers a €149 Million Route to Immediate Superyacht Ownership", summary: "Forbes reports that the 95.2-metre Lürssen Whisper, commissioned by billionaire Shahid Khan, is listed at €149 million. The broker estimates that a comparable new build could cost close to €400 million and require four to five years.", category: "Superyachts", source: "Forbes", articleUrl: "https://www.forbes.com/sites/deajusufi/2026/08/29/this-superyacht-could-save-its-next-owner-250-million-and-five-years/", imageUrl: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "altea-hills-7-million-mediterranean-villa-2026", title: "A $7 Million Altea Hills Villa Brings Mediterranean Privacy to Market", summary: "Robb Report reports that a 9,600-square-foot villa in the Altea Hills enclave near Alicante is being marketed for just under $7 million. The three-level home includes Mediterranean views, an infinity pool, cinema, gym, sauna and terraced gardens.", category: "Real Estate", source: "Robb Report", articleUrl: "https://robbreport.com/shelter/homes-for-sale/spain-altea-hills-villa-1238609439/", imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "electric-air-taxis-limited-commercial-services-2026", title: "Electric Air Taxis Near Their First Limited Commercial Services", summary: "Robb Report reports that the first limited eVTOL passenger services could commence during 2026, potentially led by Joby Aviation. Early adoption is expected to centre on premium urban journeys between airports, heliports and purpose-built vertiports.", category: "Aviation", source: "Robb Report", articleUrl: "https://robbreport.com/motors/aviation/electric-air-taxis-take-flight-what-to-expect-1238574064/", imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "chanel-imprime-lion-sapphire-high-jewellery-2026", title: "Chanel’s Imprimé Lion Necklace Centres on a 20-Carat Sapphire", summary: "Robb Report reports that Chanel’s Signes & Symboles high-jewellery collection is led by the Imprimé Lion necklace, centred on a 20.66-carat Sri Lankan sapphire. The piece combines diamond details with white and rose gold and is said to require 1,800 hours of craftsmanship.", category: "Luxury", source: "Robb Report", articleUrl: "https://robbreport.com/style/jewelry/chanel-imprime-lion-necklace-1238574074/", imageUrl: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80", isFeatured: false, publishedAt },
];

function requireEnv(name) { const value = process.env[name]; if (!value) throw new Error(`${name} is not set`); return value; }
function validateBatch() {
  if (articles.length !== 12) throw new Error("Expected exactly 12 articles");
  if (articles.filter(article => article.isFeatured).length !== 2) throw new Error("Expected exactly 2 featured articles");
  const slugs = new Set();
  for (const article of articles) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(article.slug)) throw new Error(`Invalid slug: ${article.slug}`);
    if (slugs.has(article.slug)) throw new Error(`Duplicate slug: ${article.slug}`);
    if (!allowedCategories.has(article.category)) throw new Error(`Invalid category: ${article.category}`);
    if (!/^https:\/\/images\.unsplash\.com\/photo-[A-Za-z0-9-]+\?w=800&q=80$/.test(article.imageUrl)) throw new Error(`Invalid Unsplash URL: ${article.slug}`);
    if (article.publishedAt.toISOString() !== "2026-09-03T00:00:00.000Z") throw new Error(`Invalid publication date: ${article.slug}`);
    if (!article.title || !article.summary || !article.source || !article.articleUrl) throw new Error(`Missing required field: ${article.slug}`);
    slugs.add(article.slug);
  }
}

try {
  validateBatch();
  const secret = new TextEncoder().encode(requireEnv("JWT_SECRET"));
  const now = Math.floor(Date.now() / 1000);
  const token = await new SignJWT({ openId: requireEnv("OWNER_OPEN_ID"), appId: requireEnv("VITE_APP_ID"), name: process.env.OWNER_NAME || "Billionaire Collection Owner" }).setProtectedHeader({ alg: "HS256", typ: "JWT" }).setIssuedAt(now).setExpirationTime(now + 300).sign(secret);
  const response = await fetch(LIVE_ENDPOINT, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify(superjson.serialize(articles)) });
  const responseText = await response.text();
  if (!response.ok) throw new Error(`Live tRPC request failed with HTTP ${response.status}: ${responseText}`);
  console.log(JSON.stringify({ success: true, count: articles.length, response: responseText }));
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  await appendFile("/tmp/billionaire-collection-news-upsert-2026-09-03.error.log", `${new Date().toISOString()} ${message}\n`);
  console.error(message);
  process.exitCode = 1;
}
