import { appendFile } from "node:fs/promises";
import { SignJWT } from "jose";
import superjson from "superjson";

const LIVE_ENDPOINT = "https://billionairecollection.com/api/trpc/news.upsertMany";
const publishedAt = new Date("2026-09-04T00:00:00.000Z");
const allowedCategories = new Set(["Wealth", "Real Estate", "Superyachts", "Aviation", "Automotive", "Art", "Philanthropy", "Luxury", "Technology", "Markets", "Family Offices"]);

export const articles = [
  { slug: "forbes-september-2026-richest-people-global-wealth", title: "The World’s Ten Richest People Hold $2.8 Trillion", summary: "Forbes’ September ranking places Elon Musk at an estimated $892 billion and reports that the world’s ten wealthiest people collectively hold $2.8 trillion. The monthly update reflects a sharp rebound in technology-linked fortunes, alongside changing positions among the world’s largest private wealth holders.", category: "Wealth", source: "Forbes", articleUrl: "https://www.forbes.com/sites/forbeswealthteam/article/the-top-ten-richest-people-in-the-world/", imageUrl: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "palm-beach-ham-and-cheese-house-105-million-listing-2026", title: "Palm Beach’s ‘Ham and Cheese House’ Lists for $105 Million", summary: "Robb Report reports that Palm Beach’s landmark Ham and Cheese House has come to market with a $105 million price tag. The sale reflects continued interest in distinctive, established properties in one of the United States’ most concentrated luxury-residential markets.", category: "Real Estate", source: "Robb Report", articleUrl: "https://robbreport.com/shelter/homes-for-sale/ham-and-cheese-house-south-florida-palm-beach-1238619425/", imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80", isFeatured: true, publishedAt },
  { slug: "tankoa-tx450-custom-148-foot-superyacht-launch-2026", title: "Tankoa Launches Its Bespoke 148-Foot TX450 Superyacht", summary: "Robb Report reports that Tankoa has launched the fully custom TX450, a 148-foot superyacht commissioned for an experienced yachtsman from the Middle East. The launch highlights continued demand for bespoke, owner-led yacht design ahead of the Mediterranean show season.", category: "Superyachts", source: "Robb Report", articleUrl: "https://robbreport.com/motors/marine/tankoa-custom-tx450-superyacht-launch-1238616499/", imageUrl: "https://images.unsplash.com/photo-1567899378494-47b22a2ae96a?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "poland-emerges-luxury-yacht-power-player-2026", title: "Poland’s Yacht Builders Gain Ground in the Luxury Market", summary: "Robb Report profiles Poland’s growth as a luxury-yacht manufacturing centre, with local builders gaining attention for advanced construction and design. The shift broadens the pool of specialist yards serving buyers seeking highly individualised vessels.", category: "Superyachts", source: "Robb Report", articleUrl: "https://robbreport.com/motors/marine/lists/poland-luxury-yachts-1238609579/", imageUrl: "https://images.unsplash.com/photo-1544550285-f813152fb2fd?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "paul-durand-ruel-art-collection-50-million-auction-2026", title: "A $50 Million French Dealer Collection of Monets and Renoirs Heads to Auction", summary: "Robb Report, reporting from ARTnews, says a French art dealer’s collection of Monets, Renoirs and other works will soon be offered at auction. The collection’s reported $50 million value underlines continued attention on blue-chip Impressionist works in the top tier of the art market.", category: "Art", source: "Robb Report", articleUrl: "https://robbreport.com/shelter/art-collectibles/paul-durand-ruel-art-collection-auction-1238621314/", imageUrl: "https://images.unsplash.com/photo-1549490349-8643362247b5?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "range-rover-first-electric-luxury-suv-launch-2026", title: "Range Rover’s First All-Electric SUV Arrives", summary: "Robb Report reports the arrival of the first all-electric Range Rover, a significant entry for the luxury SUV segment. The launch brings an established ultra-luxury nameplate into the growing market for premium electric vehicles.", category: "Automotive", source: "Robb Report", articleUrl: "https://robbreport.com/motors/cars/range-rover-first-electric-car-1238621283/", imageUrl: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "electric-air-taxis-first-limited-commercial-services-2026", title: "Electric Air Taxis Move Closer to Limited Premium Service", summary: "Robb Report reports that the first limited commercial eVTOL passenger services could begin during 2026, with early routes designed for premium urban connections. The sector is focused on short journeys linking airports, heliports and emerging vertiport networks.", category: "Aviation", source: "Robb Report", articleUrl: "https://robbreport.com/motors/aviation/electric-air-taxis-take-flight-what-to-expect-1238574064/", imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "idaho-riverfront-estate-charity-luxury-auction-2026", title: "Idaho Riverfront Trophy Estate to Sell at Charity-Linked Luxury Auction", summary: "Yahoo Finance reports that a 12,700-square-foot riverfront property in American Falls, Idaho, will be sold to the highest bidder at a 17 September luxury auction. The owner has pledged the sale proceeds equally to St. Jude Children’s Research Hospital and Mayo Clinic.", category: "Philanthropy", source: "Yahoo Finance / PR Newswire", articleUrl: "https://finance.yahoo.com/real-estate/articles/idaho-riverfront-estate-sell-luxury-103000236.html", imageUrl: "https://images.unsplash.com/photo-1600585152915-d208bec867a1?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "1789-capital-polymarket-300-million-investment-2026", title: "1789 Capital Plans $300 Million Polymarket Investment", summary: "Caproasia reports that 1789 Capital intends to invest $300 million in Polymarket at a $21 billion valuation. The financing places prediction-market infrastructure among the high-profile alternative platforms attracting major private-capital interest.", category: "Markets", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/02/united-states-president-billionaire-donald-trump-age-80-eldest-son-donald-trump-jr-venture-capital-firm-1789-capital-to-invest-300-million-in-united-states-prediction-market-company-polymarket-at/", imageUrl: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "softbank-sb-energy-seven-billion-nasdaq-ipo-2026", title: "SoftBank’s SB Energy Pursues a $7 Billion Nasdaq IPO", summary: "Caproasia reports that SB Energy, a SoftBank Group subsidiary founded in 2019, has filed for a Nasdaq IPO targeting $7 billion at a $50 billion valuation. The company is building gigawatt-scale power and data-centre capacity for the AI economy.", category: "Technology", source: "Caproasia", articleUrl: "https://www.caproasia.com/2026/09/02/japan-billionaire-masayoshi-son-softbank-group-subsidiary-sb-energy-files-for-nasdaq-ipo-to-raise-7-billion-at-50-billion-valuation-founded-in-2019-by-softbank-group/", imageUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "ikonic-yachts-family-office-advisory-model-2026", title: "Ikonic Yachts Brings a Family-Office Lens to Superyacht Ownership", summary: "Forbes reports that Ikonic Yachts offers integrated advice on acquisition, sale, charter and management for UHNW yacht owners. Its Sovereign platform uses historical operating data to support ownership-cost, compliance, risk and valuation discussions.", category: "Family Offices", source: "Forbes", articleUrl: "https://www.forbes.com/sites/jefffromm/2026/09/01/ultra-high-net-worth-users-get-a-family-office-view-to-super-yachts/", imageUrl: "https://images.unsplash.com/photo-1540946485063-a40da27545f8?w=800&q=80", isFeatured: false, publishedAt },
  { slug: "basil-hayden-cognac-cask-reserve-bourbon-2026", title: "Basil Hayden Releases a Cognac-Cask Reserve Bourbon", summary: "Robb Report reports that Jim Beam has introduced a Basil Hayden bourbon finished in 25-year-old Cognac casks. The launch brings a rare-cask proposition to the high-end spirits market, where provenance and limited production continue to drive collector interest.", category: "Luxury", source: "Robb Report", articleUrl: "https://robbreport.com/food-drink/spirits/basil-hayden-cognac-cask-reserve-bourbon-1238621307/", imageUrl: "https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=800&q=80", isFeatured: false, publishedAt },
];

function requireEnv(name) { const value = process.env[name]; if (!value) throw new Error(`${name} is not set`); return value; }
function validateBatch() {
  if (articles.length !== 12) throw new Error("Expected exactly 12 articles");
  if (articles.filter(article => article.isFeatured).length !== 2) throw new Error("Expected exactly 2 featured articles");
  const slugs = new Set();
  for (const article of articles) {
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(article.slug)) throw new Error(`Invalid slug: ${article.slug}`);
    if (slugs.has(article.slug)) throw new Error(`Duplicate slug: ${article.slug}`);
    if (!allowedCategories.has(article.category)) throw new Error(`Invalid category: ${article.category}`);
    if (!/^https:\/\/images\.unsplash\.com\/photo-[A-Za-z0-9-]+\?w=800&q=80$/.test(article.imageUrl)) throw new Error(`Invalid Unsplash URL: ${article.slug}`);
    if (article.publishedAt.toISOString() !== "2026-09-04T00:00:00.000Z") throw new Error(`Invalid publication date: ${article.slug}`);
    if (!article.title || !article.summary || !article.source || !article.articleUrl) throw new Error(`Missing required field: ${article.slug}`);
    slugs.add(article.slug);
  }
}

try {
  validateBatch();
  const secret = new TextEncoder().encode(requireEnv("JWT_SECRET"));
  const now = Math.floor(Date.now() / 1000);
  const token = await new SignJWT({ openId: requireEnv("OWNER_OPEN_ID"), appId: requireEnv("VITE_APP_ID"), name: process.env.OWNER_NAME || "Billionaire Collection Owner" }).setProtectedHeader({ alg: "HS256", typ: "JWT" }).setIssuedAt(now).setExpirationTime(now + 300).sign(secret);
  const response = await fetch(LIVE_ENDPOINT, { method: "POST", headers: { "content-type": "application/json", authorization: `Bearer ${token}` }, body: JSON.stringify(superjson.serialize(articles)) });
  const responseText = await response.text();
  if (!response.ok) throw new Error(`Live tRPC request failed with HTTP ${response.status}: ${responseText}`);
  console.log(JSON.stringify({ success: true, count: articles.length, response: responseText }));
} catch (error) {
  const message = error instanceof Error ? error.message : String(error);
  await appendFile("/tmp/billionaire-collection-news-upsert-2026-09-04.error.log", `${new Date().toISOString()} ${message}\n`);
  console.error(message);
  process.exitCode = 1;
}
